// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ1gZhBa6alV4flaY4Zu_Y2BAkyEnyQ4g',
    appId: '1:102751408786:web:4684004ec4913e07ac8c4b',
    messagingSenderId: '102751408786',
    projectId: 'filmlerapp-854bb',
    authDomain: 'filmlerapp-854bb.firebaseapp.com',
    storageBucket: 'filmlerapp-854bb.appspot.com',
    measurementId: 'G-B942J070Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfqQJzKtc59T_DWwwOInpxqjW-Xlw3mEM',
    appId: '1:102751408786:android:624597bccfd239edac8c4b',
    messagingSenderId: '102751408786',
    projectId: 'filmlerapp-854bb',
    storageBucket: 'filmlerapp-854bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfSvqXQmLzXsQs2wm_hqNekOn-Yb2m_jo',
    appId: '1:102751408786:ios:16c499eb7e021d85ac8c4b',
    messagingSenderId: '102751408786',
    projectId: 'filmlerapp-854bb',
    storageBucket: 'filmlerapp-854bb.appspot.com',
    iosBundleId: 'com.example.filmlerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfSvqXQmLzXsQs2wm_hqNekOn-Yb2m_jo',
    appId: '1:102751408786:ios:757017b210c4173bac8c4b',
    messagingSenderId: '102751408786',
    projectId: 'filmlerapp-854bb',
    storageBucket: 'filmlerapp-854bb.appspot.com',
    iosBundleId: 'com.example.filmlerApp.RunnerTests',
  );
}
